name: Build

# pushされたタイミングでBuild
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # Build
    - name: Build
      run: cargo build --verbose

    # Test
    - name: Run tests
      run: cargo test --verbose
